version: '2.4'
services:
  ui:
    image: registry2.swarm.devfactory.com/aurea-zero-based/ui:${ENV_NAME}
    container_name: ${ENV_NAME}_aurea-zero-based_ui
    network_mode: bridge
    environment:
      - BACKEND_URL
    ports:
      - ${PORT_UI}:80
    cpu_quota: 300000
    mem_limit: 6GB
    restart: always
    labels:
     - "com.trilogy.company=aurea"
     - "com.trilogy.team=KayakoRewrite.Backend"
     - "com.trilogy.product=aurea-zero-based"
     - "com.trilogy.service=ui"
     - "com.trilogy.stage=${ENV_NAME}"
     - "com.trilogy.maintainer.email=alexander.yushchenko@aurea.com"
     - "com.trilogy.maintainer.skype=sahkalit"
  api:
    image: registry2.swarm.devfactory.com/aurea-zero-based/api:${ENV_NAME}
    container_name: ${ENV_NAME}_aurea-zero-based_api
    network_mode: bridge
    environment:
      - SPRING_MAIL_USERNAME
      - SPRING_MAIL_PASSWORD
      - BACKEND_URL
    ports:
      - ${PORT_API}:8080
    cpu_quota: 300000
    mem_limit: 6GB
    restart: always
    labels:
      - "com.trilogy.company=aurea"
      - "com.trilogy.team=KayakoRewrite.Backend"
      - "com.trilogy.product=aurea-zero-based"
      - "com.trilogy.service=api"
      - "com.trilogy.stage=${ENV_NAME}"
      - "com.trilogy.maintainer.email=alexander.yushchenko@aurea.com"
      - "com.trilogy.maintainer.skype=sahkalit"
