version: '2.4'
services:
  ui:
    image: registry2.swarm.devfactory.com/aurea-zero-based/ui:${ENV_STAGE}
    network_mode: bridge
    environment:
      - BACKEND_URL
    ports:
      - 80
    cpu_quota: 300000
    mem_limit: 6GB
    restart: always
    labels:
     - "SERVICE_NAME=${ENV_STAGE}_aurea-zero-based${ENV_SUFFIX}_ui"
     - "SERVICE_TAGS=trilogy.client_req_max_size=100M,trilogy.expose-v2,trilogy.http,trilogy.internal,trilogy.endpoint=${AUREA_API_UI_URN}"
     - "com.trilogy.company=aurea"
     - "com.trilogy.team=KayakoRewrite.Backend"
     - "com.trilogy.product=aurea-zero-based"
     - "com.trilogy.service=ui"
     - "com.trilogy.stage=${ENV_STAGE}"
     - "com.trilogy.maintainer.email=alexander.yushchenko@aurea.com"
     - "com.trilogy.maintainer.skype=sahkalit"
  api:
    image: registry2.swarm.devfactory.com/aurea-zero-based/api:${ENV_STAGE}
    network_mode: bridge
    environment:
      - SPRING_MAIL_USERNAME
      - SPRING_MAIL_PASSWORD
      - BACKEND_URL
      - AUREA_API_UI_URL
    ports:
      - 8080
    cpu_quota: 300000
    mem_limit: 6GB
    restart: always
    labels:
      - "SERVICE_NAME=${ENV_STAGE}_aurea-zero-based${ENV_SUFFIX}_api"
      - "SERVICE_TAGS=trilogy.client_req_max_size=100M,trilogy.expose-v2,trilogy.http,trilogy.internal,trilogy.endpoint=${BACKEND_URN}"
      - "com.trilogy.company=aurea"
      - "com.trilogy.team=KayakoRewrite.Backend"
      - "com.trilogy.product=aurea-zero-based"
      - "com.trilogy.service=api"
      - "com.trilogy.stage=${ENV_STAGE}"
      - "com.trilogy.maintainer.email=alexander.yushchenko@aurea.com"
      - "com.trilogy.maintainer.skype=sahkalit"
