version: '3'

services:
  sample-zbw-ui:
    image: sample-zbw-ui:$tag
    network_mode: bridge
    container_name: sample-zbw-ui
    ports:
      - 10234:80
    deploy:
      limits:
        memory: 2000M
      mode: global
      update_config:
        delay: 10s
      restart_policy:
        condition: on-failure

  sample-zbw-api:
    image: sample-zbw-api:$tag
    network_mode: bridge
    container_name: sample-zbw-api
    ports:
      - 10233:8080
    environment:
      - SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_PASSWORD
    deploy:
      limits:
        memory: 2000M
      mode: global
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
