# IMPORTANT: If you change the prefix remember to adjust the ApiProperties object
zbw:
    # API Configuration
    api:
        title: ZBW Integration API
        license: UNLICENSED
        version: 1.0.0

        # Swagger API Configuration
        swagger:
            uiPath: /swagger-ui.html
            resourcesPath1: /swagger-resources/**
            resourcesPath2: /webjars/springfox-swagger-ui/**

        security:
            cors:
                allowedOrigins: http://localhost:4000
                allowedHeaders: Content-Type,Authorization,Pragma
                allowedMethods: POST,PUT,PATCH,GET,OPTIONS,DELETE
            authentication:
                type: Bearer
                loginPath: /auth/login
                responseHeader: Authorization
            jwt:
              secret: eyKhbFci9iJIUzRxMiN
              expiration: 2592000000

# Spring Configuration
spring:
    data:
        rest:
            basePath: /data
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create-drop

# EMBEDDED SERVER CONFIGURATION
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
server:
    error:
        path: /error

# Swagger Library Configuration
springfox:
    documentation:
        swagger:
            v2:
                path: /api-docs

# Actuator Configuration
endpoints:
    actuator:
        enabled: false
    auditevents:
        enabled: false
    autoconfig:
        enabled: false
    beans:
        enabled: false
    configprops:
        enabled: false
    dump:
        enabled: false
    env:
        enabled: false
    flyway:
        enabled: false
    health:
        enabled: true
        path: /health
    info:
        enabled: false
    loggers:
        enabled: false
    liquibase:
        enabled: false
    metrics:
        enabled: false
    mappings:
        enabled: false
    shutdown:
        enabled: false
    trace:
        enabled: false
    docs:
        enabled: false
    heapdump:
        enabled: false
    jolokia:
        enabled: false
    logfile:
        enabled: false
