aurea:
  api:
    info:
      title: Zero Based Website API
      license: UNLICENSED
      version: 1.0.0
    uiUrl: "http://localhost:4000"
    cors:
      allowedOrigins: http://localhost:4000
      maxAge: 3600
    securitySchemeKeyName: ZeroBasedWebsite

server.error.whitelabel.enabled: false

spring:
  datasource:
    url: jdbc:h2:mem:zwb_h2_db
    driver-class-name: org.h2.Driver
  data:
    rest:
      base-path: /api
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  mail:
    # AWS SES properties
    host: email-smtp.us-east-1.amazonaws.com
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 25
          auth: true
          starttls:
            enable: true
            required: true

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

security:
  oauth2:
    client:
      client-id: zwbapp
      client-secret: zwbsecret
    authorization:
      check-token-access: isAuthenticated()
