kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  namespace: "{{ namespace }}"
  name: "{{ container_hostname }}"
  labels:
    name: "{{ container_hostname }}"
  annotations:
    kubernetes.io/ingress.class: nonprod-internal
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: "{{ host }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: "{{ container_hostname }}"
          servicePort: {{ service_port }}
