apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: <role_name>
subjects:
- kind: User
  name: system:serviceaccount:<namespace>:<serviceaccount_username>
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
