aurea:
  api:
    info:
      title: Zero Based Website API
      license: UNLICENSED
      version: 1.0.0
    cors:
      allowedOrigins: http://localhost:4000, http://dlb1.aureacentral.com:10234, http://dl1.aureacentral.com:10234, http://dl6.aureacentral.com:10234
      allowedHeaders: Content-Type,Authorization,Pragma
      allowedMethods: POST,PUT,PATCH,GET,OPTIONS,DELETE
      maxAge: 3600
    securitySchemeKeyName: ZeroBasedWebsite

server.error.whitelabel.enabled: false
spring:
  profiles:
    active: mail-local
  datasource:
    url: mysql_url
    driver-class-name: com.mysql.jdbc.Driver
  data:
    rest:
      base-path: /api
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  mail:
    host: email-smtp.us-east-1.amazonaws.com
    username: ${MAIL_HOST_USERNAME}
    password: ${MAIL_HOST_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 25
          auth: true
          starttls:
            enable: true
            required: true

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

security:
  oauth2:
    client:
      client-id: zwbapp
      client-secret: zwbsecret
    authorization:
      check-token-access: isAuthenticated()

